name: Build Binaries for All Platforms

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Electron Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Platform-Specific Dependencies
      - name: Set Up Platform Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 python3-pip python3-venv \
            fakeroot dpkg rpm libnss3 libxss1 libxkbfile1 \
            libkrb5-dev g++ make
          python3 -m pip install --upgrade pip setuptools

      - name: Set Up Platform Dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          # Ensure Chocolatey is installed
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force;
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
            iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));
          }
          choco --version

          # Install dependencies
          choco install python --version=3.9
          choco install nsis
          choco install 7zip

      - name: Install Dependencies
        run: npm install

      - name: Build React Step
        run: npm run watchreact

      - name: Build Electron Step
        run: npm run watch

      - name: Electron-Builder
        run: |
          npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || 'linux' }}
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: dist/ # Ensure this matches your electron-builder output directory
