name: Build Binaries for All Platforms

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Electron Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node 16 (example)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install
        # or yarn install if your project uses yarn

      - name: Build React Step
        run: npm run watchreact

      - name: Build Electron Step
        run: npm run watch

      - name: Electron-Builder
        run: |
          npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || matrix.os == 'macos-latest' && 'mac' || 'linux' }}
        # or specify a config with "npx electron-builder -c electron-builder.config.js"

      # Upload artifacts so you can download them from the Actions page
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: dist/
          # dist/ is the typical output directory for electron-builder
