name: Sync from Upstream

on:
  schedule:
    - cron: "0 * * * *"  # once every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/voideditor/void.git
          git fetch upstream

      - name: Merge upstream into main
        run: |
          git checkout main
          git merge upstream/main

      - name: Push changes to fork
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
