name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: "bnowak008/void"

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/voideditor/void.git

      - name: Fetch and Merge Upstream
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
